### ISSUE TITLE
Additional access required to perftools in order to set up supporting services

### ISSUE THREAD

**Issue by lauripiisang** [perftools/xhgui-collector#1]
@markstory I'll need to set up packagist & scrutinizer, perhaps other services.  
This will require me to have relevant access rights in perftools organization.

I'm not sure how to even connect "as organization" to packagist, so you could do that I guess, 
but essentially I cannot see project settings link for this project.

**Comment by markstory** [comment]
I can take care of getting those things setup tonight.

**Comment by markstory** [comment]
Packagist and scrutinizer are setup now.

**Comment by lauripiisang** [comment]
that's not really what I asked

**Comment by markstory** [comment]
Ok. You should have admin rights on the repositories now. Will that help?

**Comment by lauripiisang** [comment]
@markstory I am still not marked a maintainer in packagist, so I cannot update  to webhook, as github as deprecated. Why not mark me as an owner in the group?

**Comment by markstory** [comment]
I can't seem to get a password reset email out of Packagist, but when I do I'll add you as a maintainer/owner in packagist.
