### ISSUE TITLE
Any plan to support Php7

### ISSUE THREAD

**Issue by nmsobri** [perftools/xhgui-collector#16]
Since php deprecated mongo extension and favor for mongodb, are you plan to update your library?

**Comment by markstory** [comment]
It should already work with PHP7 as we can use either extension version. Are you getting errors when running xhgui with the mongodb extension?

**Comment by nmsobri** [comment]
@markstory Yes you were correct..I got an error when use `mongodb` extension..There is couple of class got deprecated with that extension..Some of the class got deprecated: 

- MongoDate
- MongoId

So basically i cant make your library work with Php7.2

**Comment by hitrain** [comment]
use this composer require alcaeus/mongo-php-adapter
and will work
