### ISSUE TITLE
mongodb connections count is a problem

### ISSUE THREAD

**Issue by maxwelldu** [perftools/xhgui-collector#17]
send data to mongodb after collection data, no close mongo connection function is called. so the mongodb connection count is increase continue, finally mongodb connection is arrive the available connection number.

**Comment by maxwelldu** [comment]
did you use this application in product environment in any project?

**Comment by markstory** [comment]
@maxwelldu No. Personally I use it for local and non-production environment profiling.

**Comment by glensc** [comment]
@maxwelldu what php sapi are you using, or how are you using the integration?

because typical apache sapi or fcgi sapi, frees all resources on request shutdown, so it should be closing mongo connections as well.

**Comment by glensc** [comment]
this project is archived, please submit new issue profiler project if you get the details needed for debugging:
- https://github.com/perftools/php-profiler
