### ISSUE TITLE
Polyglot Xhgui_Saver_Pdo

### ISSUE THREAD

**Issue by 1ma** [perftools/xhgui-collector#26]
Despite its name the first version (1.7.0) of the Xhgui_Saver_Pdo only works for SQLite3+ due to a bit of non-ISO SQL.

At the very least it should support MySQL/MariaDB, PostgreSQL and SQLite transparently to the end user.

**Comment by markstory** [comment]
Supporting more than one SQL dialect will require a database abstraction layer like cakephp/database or doctrine/dbal

**Comment by 1ma** [comment]
I don't think it'll be mandatory. On the worst case (if we can't write SQL that runs on all 3 vendors) we can query the PDO object for the underlying driver and branch out:

```
[1] boris> $pdo = new PDO('sqlite::memory:');
// object(PDO)(
// 
// )
[2] boris> $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
// 'sqlite'
```

**Comment by markstory** [comment]
I don't think rolling another database abstraction layer is the best use of the limited time folks have for this project.

Using a library will help make query building easier and make schema management simpler.

**Comment by glensc** [comment]
Savers will be imported to main xgui app (and this project archived):
- https://github.com/perftools/xhgui/issues/309

and there will have more freedom on how to code the persistence layer.
