### ISSUE TITLE
Relational indexes

### ISSUE THREAD

**Issue by 1ma** [perftools/xhgui-collector#27]
The first version (1.7.0) of Xhgui_Saver_Pdo creates a results table if it doesn't exist, but it never creates any index besides the primary key. With only a few traces in the table xhgui works OK, but this table should have all the indexes it needs to keep answering quickly as the number of stored traces grows.

These indexes should only be created when the table did not exist. However I haven't yet determined the exact indexes it'll need.

**Comment by glensc** [comment]
Savers will be imported to main xgui app (and this project archived):
- https://github.com/perftools/xhgui/issues/309

this should be addressed in that project once savers imported.
