### ISSUE TITLE
Skipping built-in functions for Tideways XHProf extension

### ISSUE THREAD

**Issue by panychek** [perftools/xhgui-collector#32]
Hi. I use this collector along with the `tideways_xhprof` extension and I don't want to profile PHP built-in functions (using the `TIDEWAYS_XHPROF_FLAGS_NO_BUILTINS` flag).
Am I right to assume there's no way to do that at the moment, since [this call](https://github.com/perftools/xhgui-collector/blob/master/external/header.php#L101) doesn't take options?

**Comment by markstory** [comment]
Not right now, but we accept pull requests :smile:

**Comment by panychek** [comment]
Well, I'd suggest then creating a new optional parameter in the XHGui config file - say, `'profiler.flags'`.
If it's there, we pass the value to the appropriate `_enable()` function instead of the defaults.
What do you think?

**Comment by Yivan** [comment]
Hello,

This feature of abilities to customize flags will be really need. Because performance are a lot better by disabling CPU flags too (see please: https://github.com/perftools/xhgui-collector/issues/35).
They are native parameters of Xhprof, so should be customizable with this xghui middleware.

Thanks.

**Comment by glensc** [comment]
This seems to be solved via 1.8.0: #32

**Comment by Yivan** [comment]
@glensc Thanks !

Are you sure ? I checked the code and we have:

```
    $flags = TIDEWAYS_FLAGS_CPU | TIDEWAYS_FLAGS_MEMORY | TIDEWAYS_FLAGS_NO_SPANS;

    if ($skipBuiltIn) {
        $flags |= TIDEWAYS_FLAGS_NO_BUILTINS;
    }
```

What is the way to disable TIDEWAYS_FLAGS_CPU  for instance ? This one is pretty greddy, so disabling it bring a lot more faster website when xhprof is activated.

Thanks

**Comment by glensc** [comment]
@Yivan yes, read the original issue description.

don't hijack random issues and add more topics there.

I've left a comment for you in https://github.com/perftools/xhgui-collector/issues/35

**Comment by Yivan** [comment]
@glensc Sorry my intend was really not hijacking this issue, it's an error from my part i was thinking built-in function where talking about the default parameters (CPU flags, etc...), but you are right subject is TIDEWAYS_XHPROF_FLAGS_NO_BUILTINS. Issue 35 is the one for my subject. Best regards.
