### ISSUE TITLE
Update composer.json for better dependencies management

### ISSUE THREAD

**Issue by Yivan** [perftools/xhgui-collector#34]
Hello,

Thanks for this nice xhgui !

It would be great, just to improve installation step, to no suggest but require the dependencies.
If you want to stay php>=7 AND php<7, you could use something like https://stackoverflow.com/a/34211576 (composer will determine himself the used php version)

As it was not clear i had to install `php7.3-ext-mongodb` manually and require `alcaeus/mongo-php-adapter`.

You should dropin the support php<7 (old xhprof don't support it) or at least say in the README.md that we must check manually the required dependancies in the suggest section of the composer.json.

Thanks!

**Comment by markstory** [comment]
I think it might be time to start preferring php7 setups. Php5 is end of life and new installs should not be using php 5 anymore.

**Comment by glensc** [comment]
this project is obsolete, use perftools/php-profiler.

that project deliberately supports older versions (as typically you need to profile some legacy app) and how to set up extensions is very well documented in project readme.
