### ISSUE TITLE
Allow to customize flags as environment parameters

### ISSUE THREAD

**Issue by Yivan** [perftools/xhgui-collector#35]
Hello,

I would like to submit an improvement of the actual https://github.com/perftools/xhgui-collector/blob/master/external/header.php

It doesn't allow to customize flags. We should be able to customize them the same way it is possible using them with the php native xhprof call (https://github.com/tideways/php-xhprof-extension). Actually flags are hardocded in the header (https://github.com/perftools/xhgui-collector/blob/master/external/header.php#L110), it doesn't make sense.

Is there any reason for this hardcoding of parameters which are customizable on Xhrpof?

This is particularly an issue because TIDEWAYS_XHPROF_FLAGS_CPU take a lot of time.
On a symfony app:
- without the xhprof extension: 0.9s
- with the xhprof extension using xghui: 3 to 6 sec (really too long)
- with the xhprof extension using xghui but disabling TIDEWAYS_XHPROF_FLAGS_CPU  (by editing directly external/header.php): 1.1 sec (great!)

As there is no way to edit external/header.php or we would need to maintain an external file doing the same but outside the composer package which is not really a good way, this issue is to allow passing flags as options/environment parameters.

Maybe linked to https://github.com/perftools/xhgui-collector/issues/32 and both could be resolved the same.

Thanks!

**Comment by markstory** [comment]
Making the flags controlled through the configuration file would be great. That would let people either use either application logic or environment variables as necessary.

**Comment by glensc** [comment]
I suggest to use https://github.com/perftools/php-profiler

I'm currently adding `NO_BUILTINS` and tideways_xhprof v5 support there, i expect to release it as 0.2.0.

**Comment by Yivan** [comment]
Thanks @glensc ! This way parameters of profiling can be configured yes.
This issue can be closed so.
Best regards

**Comment by glensc** [comment]
@Yivan so, the solution offered by `perftools/php-profiler` works for you?

**Comment by Yivan** [comment]
I didn't tested it, but yes as we can configure parameters it should do the job. I imagine it could be connected with the perftools/xhgui-collector to display datas in GUI.

**Comment by glensc** [comment]
use perftools/php-profiler, this project will be archived soon
