### ISSUE TITLE
Document compatibility with 0.8.x

### ISSUE THREAD

**Issue by Krinkle** [perftools/xhgui-collector#9]
I don't see any schema changes in [the release notes], but it'd be nice if we could document here that XHGui Collector is in fact compatible with xhgui 0.8.1, for example.

/cc @ed-piisang, @markstory

**Comment by markstory** [comment]
Sounds like a great idea. Any chance you'd be interested in sending a pull request with the changes you think should be made?

**Comment by Krinkle** [comment]
@markstory Sure thing. I'm happy to do the writing, but I'm not currently able to easily confirm/verify the actual claim of compatibility. So you're saying it is still compatible, right?

**Comment by markstory** [comment]
> So you're saying it is still compatible, right?

Yes.
